### 1. What makes NumPy.shape() different from NumPy.size() ?

1. numpy.shape() --> Function returns the shape of an array. Shape means (Row X Columns X Dimension) that is the number of elements in each                      dimension. 
2. numpy.size() --> Function count the number of elements along a given axes in which rows and columns are being treated as                         elements. By default, counts the total number of elements in an array.

In [10]:
import numpy as np

# 1-d array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# numpy.shape() -->
print(np.shape(arr))

# numpy.size() -->

# By default gives total number of elements in the array
print(np.size(arr))
# 0 corresponds to Number of rows along x-axis
print(np.size(arr, 0))
# 1 corresponds to Number of columns along y-axis
print(np.size(arr, 1))

print('----******************----')

# 2-d array
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(np.shape(arr1))
print(np.size(arr1))
print(np.size(arr1, 0))
print(np.size(arr1, 1))

print('----******************----')

# 3-d array
arr2 = np.array([[[1, 2, 7], [3, 4, 3]], [[5, 6, 9], [7, 8, 10]]])

print(np.shape(arr2))
print(np.size(arr2))
print(np.size(arr2, 0))
print(np.size(arr2, 1))

(2, 4)
8
2
4
----******************----
(2, 2, 2)
8
2
2
----******************----
(2, 2, 3)
12
2
2


### 2. In NumPy, describe the idea of broadcasting ?

To perform mathematical operations between arrays of different shapes numpy broadcasting is used. Broadcasting in python simply means reshaping the vector and complete the mathematical operation element-wise. 

In [13]:
a = np.random.randn(2,3)
print(a)
print(a.shape)

print('***********************')

b = np.random.randn(2,1)
print(b)
print(b.shape)

print('***********************')

c = a+b
print(c)
print(c.shape)

[[ 1.40556148  0.50999116 -0.98967655]
 [ 1.78195427  0.41347894  1.11654289]]
(2, 3)
***********************
[[-0.03471081]
 [-0.65327618]]
(2, 1)
***********************
[[ 1.37085067  0.47528035 -1.02438737]
 [ 1.12867809 -0.23979724  0.46326672]]
(2, 3)


This is broadcasting, where b (2, 1) column vector is copied three times (2, 3) so that it can be summed to each column of a.

In [14]:
a = np.random.randn(4,3)
print(a)
print(a.shape)

print('***********************')

b = np.random.randn(3,2)
print(b)
print(b.shape)

print('***********************')

c = a*b
print(c)
print(c.shape)

[[-1.73059692  0.41880047 -0.76126088]
 [-0.42576705 -0.47801797 -0.11841531]
 [-0.0456759  -0.38737266 -0.40423731]
 [-0.41854442 -0.98299125 -1.70282992]]
(4, 3)
***********************
[[ 0.71990321 -0.96114051]
 [-0.06636599 -0.76704147]
 [ 1.68143824 -1.71249278]]
(3, 2)
***********************


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In numpy the '*' operator indicates element-wise multiplication. Here , the broadcasting does not happen because of the shape of 'b' vector. 'b' should have been something like (4,1) or (1,3). In the above case the computation cannto happen because the sizes does not match. It's going to be 'ERROR'.

np.dot(a,b) performs a Matrix-Matrix Multiplication.

a*b or np.multiply() performs Element-wise Multiplication.

In [15]:
a = np.random.randn(4,3)
print(a)
print(a.shape)

print('***********************')

b = np.random.randn(4,1)
print(b)
print(b.shape)

print('***********************')

c = a*b
print(c)
print(c.shape)

[[ 1.7534319  -0.88385034 -0.82143967]
 [-0.83606438  1.6192847  -2.31091266]
 [ 0.14740662  0.88092028 -0.35276315]
 [ 0.70171484  0.08423218 -2.42325675]]
(4, 3)
***********************
[[-1.45210142]
 [ 1.73631299]
 [-1.49471146]
 [ 0.23450085]]
(4, 1)
***********************
[[-2.54616096  1.28344033  1.19281371]
 [-1.45166945  2.81158506 -4.01246769]
 [-0.22033037 -1.31672164  0.52727913]
 [ 0.16455272  0.01975252 -0.56825576]]
(4, 3)


In [16]:
a = np.random.randn(4,3)
print(a)
print(a.shape)

print('***********************')

b = np.random.randn(1,3)
print(b)
print(b.shape)

print('***********************')

c = a*b
print(c)
print(c.shape)

[[-1.12153935  0.24648958 -0.92948118]
 [-0.25188437 -0.48472242 -1.64703969]
 [-1.10927438  0.52444037  0.11107015]
 [ 0.07342198  2.34348204  0.31716219]]
(4, 3)
***********************
[[-1.12411395  1.30959542 -0.95207102]]
(1, 3)
***********************
[[ 1.26073804  0.32280162  0.88493209]
 [ 0.28314674 -0.63479027  1.56809876]
 [ 1.24695081  0.6868047  -0.10574667]
 [-0.08253468  3.06901335 -0.30196093]]
(4, 3)


### 3. What makes Python better than other libraries for numerical computation ?

There is an extension of Python, commonly called Numerical Python (NumPy), which offers efficient array computations. 
Numerical Python has a fixed-size, homogeneous (fixed-type), multi-dimensional array type and lots of functions for various array operations. 
In deep learning we mostly use matrices and vectors therefore numpy is more useful. The data structures we use in numpy to represent these shapes like matrices and vectors are called as Numpy arrays.
NumPy provides optimized data structures and basic routines for manipulating multidimensional numerical data.
NumPy underlies many other numeric and algorithm libraries available for Python, such as: SciPy, matplotlib, pandas, OpenCV’s Python API, and more.

Ndarray – the basic NumPy data type:
1. NumPy ndarray’s are: Typed, Fixed size, Fixed dimensionality
2. An ndarray can be constructed from:

   a. Conversion from a Python list, set, tuple, or similar data structure

   b. NumPy initialization routines
   
   c. Copies or computations with other ndarray’s
   
   d. NumPy-based functions as a return value

Ndarray:
1. Intended to store and process (mostly) numeric data
2. Typed
3. N-dimensions: Chosen at creation time
4. Fixed size: Chosen at creation time
5. Accessed with [ ] notation and integer indices

The basic data type is a class called ndarray.
1. The object has a data that describes the array (data type, number of dimensions, number of elements, memory format, etc.)
2. A contiguous array in memory containing the data.

In [17]:
import numpy as np
y=np.array([1,2,3]) # numpy array initialization using python list
y[1]

2

In [19]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [23]:
# data type can be assigned at creation time
c = np.array([1,2,3], dtype='int8')
c.dtype

dtype('int8')

In [24]:
# Conversion from one type to another is done with the astype() method
b = a.astype('float')
b.dtype

dtype('float64')

Ndarray memory storage
1. The memory allocated by an ndarray --> Storage for the data: N elements * bytes-per-element --> 4 bytes for 32-bit integers, 8 bytes for 64-bit floats (doubles), 1 byte for 8-bit characters etc.

2. A small amount of memory is used to store info about the ndarray (~few dozen bytes)

numpy.where --> numpy.where(condition, [x, y])
1. Condition: some Boolean condition applied to an ndarray
2. x, y: Optional variables to choose from. x is for condition == True, y is for condition == False.
3. All three arguments must apply to ndarray’s.


In [29]:
a=np.linspace(-1,1,5)
print(a)
# Returns a TUPLE containing the INDICES where the condition is True!
b = np.where(a <= 0)
print(b)
c = np.where(a <= 0, -a, 20*a)
print(c)

[-1.  -0.5  0.   0.5  1. ]
(array([0, 1, 2], dtype=int64),)
[ 1.   0.5 -0.  10.  20. ]


### By default operators work element-by-element

In [33]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
c = a / b # c is an ndarray
print(c)
print(type(c))
print(a * b)
print(a + b)
print(a - b)
print(a / b)
print(-2 * a + b)

[0.25       0.4        0.5        0.57142857]
<class 'numpy.ndarray'>
[ 4 10 18 28]
[ 5  7  9 11]
[-3 -3 -3 -3]
[0.25       0.4        0.5        0.57142857]
[ 2  1  0 -1]


### Vectors are applied row-by-row to matrices. The length of the vector must match the width of the row.

In [34]:
a = np.array([2,2,2,2])
c = np.array([[1,2,3,4],
              [4,5,6,7],
              [1,1,1,1],
              [2,2,2,2]])
a + c

array([[3, 4, 5, 6],
       [6, 7, 8, 9],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

### Vector/matrix multiplication can be done using the dot(), cross() functions, or @ operator

In [36]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
print(np.dot(a, b)) 
print(a @ b)
print(np.cross(a,b))

[[4 1]
 [2 2]]
[[4 1]
 [2 2]]
[ 1 -2]


### 4. How does NumPy deal with files ?

### NumPy I/O
1. When reading files you can use standard Python, use lists, allocate ndarrays and fill them.
2. Or use any of NumPy’s I/O routines that will directly generate ndarrays.
3. The best way depends on the structure of your data.
4. If dealing with structured numeric data (tables of numbers, etc.) NumPy is easier and faster. 

### Some numpy file reading options --> .npz and .npy file formats
1. .npy files store a single NumPY variable in a binary format.
2. .npz files store multiple NumPy Variables in a file.
3. h5py is a library that reads HDF5 files into ndarrays
4. The I/O routines allow for flexible reading from a variety of text file formats


In [39]:
import numpy as np
np.save # save .npy
np.savez # save .npz
# ditto, with compression
np.savez_compressed
np.load # load .npy

<function numpy.load>

To import Text files into Numpy Arrays, we have two functions in Numpy: 
1. numpy.loadtxt( ) – Used to load text file data
2. numpy.genfromtxt( ) – Used to load data from a text file, with missing values handled as defined.
3. numpy.loadtxt( ) is equivalent function to numpy.genfromtxt( ) when no data is missing.

In [ ]:
import numpy as np
# Text file data converted to integer data type
File_data = np.loadtxt("example1.txt", dtype=int)
print(File_data)

In [ ]:
import numpy as np
# skipping first row
# converting file data to string
data = np.loadtxt("example2.txt", skiprows=1, dtype='str')
print(data)

In [ ]:
import numpy as np
Data = np.genfromtxt("example4.txt", dtype=str,
                     encoding=None, delimiter=",")
print(Data)

In [ ]:
import numpy as np
# skipping last line in the file
Data = np.genfromtxt("example5.txt", dtype=str,
                     encoding=None, skip_footer=1)
print(Data)

### 5. Mention the importance of NumPy.empty() 

numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.
Parameters :

1. shape : Number of rows
2. order : C_contiguous or F_contiguous
3. dtype : [optional, float(by Default)] Data type of returned array.  

In [40]:
# Python Programming illustrating
# numpy.empty() method

import numpy as np

b = np.empty(2, dtype = int)
print("Matrix b : \n", b)

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [ 1 -2]

Matrix a : 
 [[4 1]
 [2 2]]

Matrix c : 
 [[6.52e-322 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 5.12e-321]
 [0.00e+000 0.00e+000 1.98e-323]]


empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster.